/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as AdminRouteRouteImport } from './app/_admin/route'
import { Route as IndexRouteImport } from './app/index'
import { Route as AuthUnauthorizedModuleRouteImport } from './app/_auth/unauthorized-module'
import { Route as AuthUnauthorizedRouteImport } from './app/_auth/unauthorized'
import { Route as AuthLogoutRouteImport } from './app/_auth/logout'
import { Route as AuthLoginRouteImport } from './app/_auth/login'
import { Route as AdminSettingsRouteRouteImport } from './app/_admin/settings/route'
import { Route as AdminVehiclesIndexRouteImport } from './app/_admin/vehicles/index'
import { Route as AdminServicesIndexRouteImport } from './app/_admin/services/index'
import { Route as AdminRidesIndexRouteImport } from './app/_admin/rides/index'
import { Route as AdminReviewsIndexRouteImport } from './app/_admin/reviews/index'
import { Route as AdminReportsIndexRouteImport } from './app/_admin/reports/index'
import { Route as AdminPaymentsIndexRouteImport } from './app/_admin/payments/index'
import { Route as AdminDriversIndexRouteImport } from './app/_admin/drivers/index'
import { Route as AdminDashboardIndexRouteImport } from './app/_admin/dashboard/index'
import { Route as AdminClientsIndexRouteImport } from './app/_admin/clients/index'
import { Route as AdminBookingsIndexRouteImport } from './app/_admin/bookings/index'
import { Route as AdminRidesNewRouteImport } from './app/_admin/rides/new'
import { Route as AdminRidesLiveRouteImport } from './app/_admin/rides/live'
import { Route as AdminDriversNewRouteImport } from './app/_admin/drivers/new'
import { Route as AdminClientsRatesRouteImport } from './app/_admin/clients/rates'
import { Route as AdminClientsPricingRatesRouteImport } from './app/_admin/clients/pricing-rates'
import { Route as AdminClientsPricingRouteImport } from './app/_admin/clients/pricing'
import { Route as AdminSettingsVehicleConfigRouteRouteImport } from './app/_admin/settings/vehicle-config/route'
import { Route as AdminSettingsUserManagementRouteRouteImport } from './app/_admin/settings/user-management/route'
import { Route as AdminVehiclesNewIndexRouteImport } from './app/_admin/vehicles/new/index'
import { Route as AdminSettingsTaxRatesIndexRouteImport } from './app/_admin/settings/tax-rates/index'
import { Route as AdminSettingsPricingConfigIndexRouteImport } from './app/_admin/settings/pricing-config/index'
import { Route as AdminSettingsPdfTemplatesIndexRouteImport } from './app/_admin/settings/pdf-templates/index'
import { Route as AdminSettingsNotificationsIndexRouteImport } from './app/_admin/settings/notifications/index'
import { Route as AdminSettingsGenerateNumbersIndexRouteImport } from './app/_admin/settings/generate-numbers/index'
import { Route as AdminSettingsCompanyDetailsIndexRouteImport } from './app/_admin/settings/company-details/index'
import { Route as AdminSettingsBookingRoutesIndexRouteImport } from './app/_admin/settings/booking-routes/index'
import { Route as AdminSettingsAdvancedIndexRouteImport } from './app/_admin/settings/advanced/index'
import { Route as AdminServicesNewIndexRouteImport } from './app/_admin/services/new/index'
import { Route as AdminReportsAuditsIndexRouteImport } from './app/_admin/reports/audits/index'
import { Route as AdminClientsNewIndexRouteImport } from './app/_admin/clients/new/index'
import { Route as AdminBookingsNewIndexRouteImport } from './app/_admin/bookings/new/index'
import { Route as AdminVehiclesVehicleIdViewRouteImport } from './app/_admin/vehicles/$vehicleId.view'
import { Route as AdminVehiclesVehicleIdEditRouteImport } from './app/_admin/vehicles/$vehicleId.edit'
import { Route as AdminServicesServiceIdViewRouteImport } from './app/_admin/services/$serviceId.view'
import { Route as AdminServicesServiceIdEditRouteImport } from './app/_admin/services/$serviceId.edit'
import { Route as AdminRidesRideIdViewRouteImport } from './app/_admin/rides/$rideId.view'
import { Route as AdminRidesRideIdEditRouteImport } from './app/_admin/rides/$rideId.edit'
import { Route as AdminDriversDriverIdViewRouteImport } from './app/_admin/drivers/$driverId.view'
import { Route as AdminDriversDriverIdEditRouteImport } from './app/_admin/drivers/$driverId.edit'
import { Route as AdminClientsDataClientIdRouteImport } from './app/_admin/clients/data/$clientId'
import { Route as AdminClientsClientIdViewRouteImport } from './app/_admin/clients/$clientId.view'
import { Route as AdminClientsClientIdPdfRouteImport } from './app/_admin/clients/$clientId.pdf'
import { Route as AdminClientsClientIdEditRouteImport } from './app/_admin/clients/$clientId.edit'
import { Route as AdminBookingsBookingIdViewRouteImport } from './app/_admin/bookings/$bookingId.view'
import { Route as AdminBookingsBookingIdEditRouteImport } from './app/_admin/bookings/$bookingId.edit'
import { Route as AdminSettingsVehicleConfigVehicleTypesIndexRouteImport } from './app/_admin/settings/vehicle-config/vehicle-types/index'
import { Route as AdminSettingsVehicleConfigTonnagesIndexRouteImport } from './app/_admin/settings/vehicle-config/tonnages/index'
import { Route as AdminSettingsVehicleConfigDriveTrainsIndexRouteImport } from './app/_admin/settings/vehicle-config/drive-trains/index'
import { Route as AdminSettingsVehicleConfigCarModelsIndexRouteImport } from './app/_admin/settings/vehicle-config/car-models/index'
import { Route as AdminSettingsVehicleConfigCarBrandsIndexRouteImport } from './app/_admin/settings/vehicle-config/car-brands/index'
import { Route as AdminSettingsUserManagementUsersIndexRouteImport } from './app/_admin/settings/user-management/users/index'
import { Route as AdminSettingsUserManagementRolesIndexRouteImport } from './app/_admin/settings/user-management/roles/index'
import { Route as AdminSettingsUserManagementPermissionsIndexRouteImport } from './app/_admin/settings/user-management/permissions/index'
import { Route as AdminSettingsUserManagementUsersNewIndexRouteImport } from './app/_admin/settings/user-management/users/new/index'
import { Route as AdminSettingsUserManagementUsersUserIdViewRouteImport } from './app/_admin/settings/user-management/users/$userId.view'
import { Route as AdminSettingsUserManagementUsersUserIdEditRouteImport } from './app/_admin/settings/user-management/users/$userId.edit'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUnauthorizedModuleRoute = AuthUnauthorizedModuleRouteImport.update({
  id: '/_auth/unauthorized-module',
  path: '/unauthorized-module',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUnauthorizedRoute = AuthUnauthorizedRouteImport.update({
  id: '/_auth/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/_auth/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRouteRoute = AdminSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminVehiclesIndexRoute = AdminVehiclesIndexRouteImport.update({
  id: '/vehicles/',
  path: '/vehicles/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminServicesIndexRoute = AdminServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRidesIndexRoute = AdminRidesIndexRouteImport.update({
  id: '/rides/',
  path: '/rides/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReviewsIndexRoute = AdminReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsIndexRoute = AdminReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPaymentsIndexRoute = AdminPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDriversIndexRoute = AdminDriversIndexRouteImport.update({
  id: '/drivers/',
  path: '/drivers/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClientsIndexRoute = AdminClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBookingsIndexRoute = AdminBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRidesNewRoute = AdminRidesNewRouteImport.update({
  id: '/rides/new',
  path: '/rides/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRidesLiveRoute = AdminRidesLiveRouteImport.update({
  id: '/rides/live',
  path: '/rides/live',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDriversNewRoute = AdminDriversNewRouteImport.update({
  id: '/drivers/new',
  path: '/drivers/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClientsRatesRoute = AdminClientsRatesRouteImport.update({
  id: '/clients/rates',
  path: '/clients/rates',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClientsPricingRatesRoute =
  AdminClientsPricingRatesRouteImport.update({
    id: '/clients/pricing-rates',
    path: '/clients/pricing-rates',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminClientsPricingRoute = AdminClientsPricingRouteImport.update({
  id: '/clients/pricing',
  path: '/clients/pricing',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsVehicleConfigRouteRoute =
  AdminSettingsVehicleConfigRouteRouteImport.update({
    id: '/vehicle-config',
    path: '/vehicle-config',
    getParentRoute: () => AdminSettingsRouteRoute,
  } as any)
const AdminSettingsUserManagementRouteRoute =
  AdminSettingsUserManagementRouteRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => AdminSettingsRouteRoute,
  } as any)
const AdminVehiclesNewIndexRoute = AdminVehiclesNewIndexRouteImport.update({
  id: '/vehicles/new/',
  path: '/vehicles/new/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsTaxRatesIndexRoute =
  AdminSettingsTaxRatesIndexRouteImport.update({
    id: '/tax-rates/',
    path: '/tax-rates/',
    getParentRoute: () => AdminSettingsRouteRoute,
  } as any)
const AdminSettingsPricingConfigIndexRoute =
  AdminSettingsPricingConfigIndexRouteImport.update({
    id: '/pricing-config/',
    path: '/pricing-config/',
    getParentRoute: () => AdminSettingsRouteRoute,
  } as any)
const AdminSettingsPdfTemplatesIndexRoute =
  AdminSettingsPdfTemplatesIndexRouteImport.update({
    id: '/pdf-templates/',
    path: '/pdf-templates/',
    getParentRoute: () => AdminSettingsRouteRoute,
  } as any)
const AdminSettingsNotificationsIndexRoute =
  AdminSettingsNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AdminSettingsRouteRoute,
  } as any)
const AdminSettingsGenerateNumbersIndexRoute =
  AdminSettingsGenerateNumbersIndexRouteImport.update({
    id: '/generate-numbers/',
    path: '/generate-numbers/',
    getParentRoute: () => AdminSettingsRouteRoute,
  } as any)
const AdminSettingsCompanyDetailsIndexRoute =
  AdminSettingsCompanyDetailsIndexRouteImport.update({
    id: '/company-details/',
    path: '/company-details/',
    getParentRoute: () => AdminSettingsRouteRoute,
  } as any)
const AdminSettingsBookingRoutesIndexRoute =
  AdminSettingsBookingRoutesIndexRouteImport.update({
    id: '/booking-routes/',
    path: '/booking-routes/',
    getParentRoute: () => AdminSettingsRouteRoute,
  } as any)
const AdminSettingsAdvancedIndexRoute =
  AdminSettingsAdvancedIndexRouteImport.update({
    id: '/advanced/',
    path: '/advanced/',
    getParentRoute: () => AdminSettingsRouteRoute,
  } as any)
const AdminServicesNewIndexRoute = AdminServicesNewIndexRouteImport.update({
  id: '/services/new/',
  path: '/services/new/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsAuditsIndexRoute = AdminReportsAuditsIndexRouteImport.update({
  id: '/reports/audits/',
  path: '/reports/audits/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClientsNewIndexRoute = AdminClientsNewIndexRouteImport.update({
  id: '/clients/new/',
  path: '/clients/new/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBookingsNewIndexRoute = AdminBookingsNewIndexRouteImport.update({
  id: '/bookings/new/',
  path: '/bookings/new/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminVehiclesVehicleIdViewRoute =
  AdminVehiclesVehicleIdViewRouteImport.update({
    id: '/vehicles/$vehicleId/view',
    path: '/vehicles/$vehicleId/view',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminVehiclesVehicleIdEditRoute =
  AdminVehiclesVehicleIdEditRouteImport.update({
    id: '/vehicles/$vehicleId/edit',
    path: '/vehicles/$vehicleId/edit',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminServicesServiceIdViewRoute =
  AdminServicesServiceIdViewRouteImport.update({
    id: '/services/$serviceId/view',
    path: '/services/$serviceId/view',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminServicesServiceIdEditRoute =
  AdminServicesServiceIdEditRouteImport.update({
    id: '/services/$serviceId/edit',
    path: '/services/$serviceId/edit',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminRidesRideIdViewRoute = AdminRidesRideIdViewRouteImport.update({
  id: '/rides/$rideId/view',
  path: '/rides/$rideId/view',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRidesRideIdEditRoute = AdminRidesRideIdEditRouteImport.update({
  id: '/rides/$rideId/edit',
  path: '/rides/$rideId/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDriversDriverIdViewRoute =
  AdminDriversDriverIdViewRouteImport.update({
    id: '/drivers/$driverId/view',
    path: '/drivers/$driverId/view',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminDriversDriverIdEditRoute =
  AdminDriversDriverIdEditRouteImport.update({
    id: '/drivers/$driverId/edit',
    path: '/drivers/$driverId/edit',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminClientsDataClientIdRoute =
  AdminClientsDataClientIdRouteImport.update({
    id: '/clients/data/$clientId',
    path: '/clients/data/$clientId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminClientsClientIdViewRoute =
  AdminClientsClientIdViewRouteImport.update({
    id: '/clients/$clientId/view',
    path: '/clients/$clientId/view',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminClientsClientIdPdfRoute = AdminClientsClientIdPdfRouteImport.update({
  id: '/clients/$clientId/pdf',
  path: '/clients/$clientId/pdf',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClientsClientIdEditRoute =
  AdminClientsClientIdEditRouteImport.update({
    id: '/clients/$clientId/edit',
    path: '/clients/$clientId/edit',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminBookingsBookingIdViewRoute =
  AdminBookingsBookingIdViewRouteImport.update({
    id: '/bookings/$bookingId/view',
    path: '/bookings/$bookingId/view',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminBookingsBookingIdEditRoute =
  AdminBookingsBookingIdEditRouteImport.update({
    id: '/bookings/$bookingId/edit',
    path: '/bookings/$bookingId/edit',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminSettingsVehicleConfigVehicleTypesIndexRoute =
  AdminSettingsVehicleConfigVehicleTypesIndexRouteImport.update({
    id: '/vehicle-types/',
    path: '/vehicle-types/',
    getParentRoute: () => AdminSettingsVehicleConfigRouteRoute,
  } as any)
const AdminSettingsVehicleConfigTonnagesIndexRoute =
  AdminSettingsVehicleConfigTonnagesIndexRouteImport.update({
    id: '/tonnages/',
    path: '/tonnages/',
    getParentRoute: () => AdminSettingsVehicleConfigRouteRoute,
  } as any)
const AdminSettingsVehicleConfigDriveTrainsIndexRoute =
  AdminSettingsVehicleConfigDriveTrainsIndexRouteImport.update({
    id: '/drive-trains/',
    path: '/drive-trains/',
    getParentRoute: () => AdminSettingsVehicleConfigRouteRoute,
  } as any)
const AdminSettingsVehicleConfigCarModelsIndexRoute =
  AdminSettingsVehicleConfigCarModelsIndexRouteImport.update({
    id: '/car-models/',
    path: '/car-models/',
    getParentRoute: () => AdminSettingsVehicleConfigRouteRoute,
  } as any)
const AdminSettingsVehicleConfigCarBrandsIndexRoute =
  AdminSettingsVehicleConfigCarBrandsIndexRouteImport.update({
    id: '/car-brands/',
    path: '/car-brands/',
    getParentRoute: () => AdminSettingsVehicleConfigRouteRoute,
  } as any)
const AdminSettingsUserManagementUsersIndexRoute =
  AdminSettingsUserManagementUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AdminSettingsUserManagementRouteRoute,
  } as any)
const AdminSettingsUserManagementRolesIndexRoute =
  AdminSettingsUserManagementRolesIndexRouteImport.update({
    id: '/roles/',
    path: '/roles/',
    getParentRoute: () => AdminSettingsUserManagementRouteRoute,
  } as any)
const AdminSettingsUserManagementPermissionsIndexRoute =
  AdminSettingsUserManagementPermissionsIndexRouteImport.update({
    id: '/permissions/',
    path: '/permissions/',
    getParentRoute: () => AdminSettingsUserManagementRouteRoute,
  } as any)
const AdminSettingsUserManagementUsersNewIndexRoute =
  AdminSettingsUserManagementUsersNewIndexRouteImport.update({
    id: '/users/new/',
    path: '/users/new/',
    getParentRoute: () => AdminSettingsUserManagementRouteRoute,
  } as any)
const AdminSettingsUserManagementUsersUserIdViewRoute =
  AdminSettingsUserManagementUsersUserIdViewRouteImport.update({
    id: '/users/$userId/view',
    path: '/users/$userId/view',
    getParentRoute: () => AdminSettingsUserManagementRouteRoute,
  } as any)
const AdminSettingsUserManagementUsersUserIdEditRoute =
  AdminSettingsUserManagementUsersUserIdEditRouteImport.update({
    id: '/users/$userId/edit',
    path: '/users/$userId/edit',
    getParentRoute: () => AdminSettingsUserManagementRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof AdminSettingsRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/logout': typeof AuthLogoutRoute
  '/unauthorized': typeof AuthUnauthorizedRoute
  '/unauthorized-module': typeof AuthUnauthorizedModuleRoute
  '/settings/user-management': typeof AdminSettingsUserManagementRouteRouteWithChildren
  '/settings/vehicle-config': typeof AdminSettingsVehicleConfigRouteRouteWithChildren
  '/clients/pricing': typeof AdminClientsPricingRoute
  '/clients/pricing-rates': typeof AdminClientsPricingRatesRoute
  '/clients/rates': typeof AdminClientsRatesRoute
  '/drivers/new': typeof AdminDriversNewRoute
  '/rides/live': typeof AdminRidesLiveRoute
  '/rides/new': typeof AdminRidesNewRoute
  '/bookings/': typeof AdminBookingsIndexRoute
  '/clients/': typeof AdminClientsIndexRoute
  '/dashboard/': typeof AdminDashboardIndexRoute
  '/drivers/': typeof AdminDriversIndexRoute
  '/payments/': typeof AdminPaymentsIndexRoute
  '/reports/': typeof AdminReportsIndexRoute
  '/reviews/': typeof AdminReviewsIndexRoute
  '/rides/': typeof AdminRidesIndexRoute
  '/services/': typeof AdminServicesIndexRoute
  '/vehicles/': typeof AdminVehiclesIndexRoute
  '/bookings/$bookingId/edit': typeof AdminBookingsBookingIdEditRoute
  '/bookings/$bookingId/view': typeof AdminBookingsBookingIdViewRoute
  '/clients/$clientId/edit': typeof AdminClientsClientIdEditRoute
  '/clients/$clientId/pdf': typeof AdminClientsClientIdPdfRoute
  '/clients/$clientId/view': typeof AdminClientsClientIdViewRoute
  '/clients/data/$clientId': typeof AdminClientsDataClientIdRoute
  '/drivers/$driverId/edit': typeof AdminDriversDriverIdEditRoute
  '/drivers/$driverId/view': typeof AdminDriversDriverIdViewRoute
  '/rides/$rideId/edit': typeof AdminRidesRideIdEditRoute
  '/rides/$rideId/view': typeof AdminRidesRideIdViewRoute
  '/services/$serviceId/edit': typeof AdminServicesServiceIdEditRoute
  '/services/$serviceId/view': typeof AdminServicesServiceIdViewRoute
  '/vehicles/$vehicleId/edit': typeof AdminVehiclesVehicleIdEditRoute
  '/vehicles/$vehicleId/view': typeof AdminVehiclesVehicleIdViewRoute
  '/bookings/new/': typeof AdminBookingsNewIndexRoute
  '/clients/new/': typeof AdminClientsNewIndexRoute
  '/reports/audits/': typeof AdminReportsAuditsIndexRoute
  '/services/new/': typeof AdminServicesNewIndexRoute
  '/settings/advanced/': typeof AdminSettingsAdvancedIndexRoute
  '/settings/booking-routes/': typeof AdminSettingsBookingRoutesIndexRoute
  '/settings/company-details/': typeof AdminSettingsCompanyDetailsIndexRoute
  '/settings/generate-numbers/': typeof AdminSettingsGenerateNumbersIndexRoute
  '/settings/notifications/': typeof AdminSettingsNotificationsIndexRoute
  '/settings/pdf-templates/': typeof AdminSettingsPdfTemplatesIndexRoute
  '/settings/pricing-config/': typeof AdminSettingsPricingConfigIndexRoute
  '/settings/tax-rates/': typeof AdminSettingsTaxRatesIndexRoute
  '/vehicles/new/': typeof AdminVehiclesNewIndexRoute
  '/settings/user-management/permissions/': typeof AdminSettingsUserManagementPermissionsIndexRoute
  '/settings/user-management/roles/': typeof AdminSettingsUserManagementRolesIndexRoute
  '/settings/user-management/users/': typeof AdminSettingsUserManagementUsersIndexRoute
  '/settings/vehicle-config/car-brands/': typeof AdminSettingsVehicleConfigCarBrandsIndexRoute
  '/settings/vehicle-config/car-models/': typeof AdminSettingsVehicleConfigCarModelsIndexRoute
  '/settings/vehicle-config/drive-trains/': typeof AdminSettingsVehicleConfigDriveTrainsIndexRoute
  '/settings/vehicle-config/tonnages/': typeof AdminSettingsVehicleConfigTonnagesIndexRoute
  '/settings/vehicle-config/vehicle-types/': typeof AdminSettingsVehicleConfigVehicleTypesIndexRoute
  '/settings/user-management/users/$userId/edit': typeof AdminSettingsUserManagementUsersUserIdEditRoute
  '/settings/user-management/users/$userId/view': typeof AdminSettingsUserManagementUsersUserIdViewRoute
  '/settings/user-management/users/new/': typeof AdminSettingsUserManagementUsersNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof AdminSettingsRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/logout': typeof AuthLogoutRoute
  '/unauthorized': typeof AuthUnauthorizedRoute
  '/unauthorized-module': typeof AuthUnauthorizedModuleRoute
  '/settings/user-management': typeof AdminSettingsUserManagementRouteRouteWithChildren
  '/settings/vehicle-config': typeof AdminSettingsVehicleConfigRouteRouteWithChildren
  '/clients/pricing': typeof AdminClientsPricingRoute
  '/clients/pricing-rates': typeof AdminClientsPricingRatesRoute
  '/clients/rates': typeof AdminClientsRatesRoute
  '/drivers/new': typeof AdminDriversNewRoute
  '/rides/live': typeof AdminRidesLiveRoute
  '/rides/new': typeof AdminRidesNewRoute
  '/bookings': typeof AdminBookingsIndexRoute
  '/clients': typeof AdminClientsIndexRoute
  '/dashboard': typeof AdminDashboardIndexRoute
  '/drivers': typeof AdminDriversIndexRoute
  '/payments': typeof AdminPaymentsIndexRoute
  '/reports': typeof AdminReportsIndexRoute
  '/reviews': typeof AdminReviewsIndexRoute
  '/rides': typeof AdminRidesIndexRoute
  '/services': typeof AdminServicesIndexRoute
  '/vehicles': typeof AdminVehiclesIndexRoute
  '/bookings/$bookingId/edit': typeof AdminBookingsBookingIdEditRoute
  '/bookings/$bookingId/view': typeof AdminBookingsBookingIdViewRoute
  '/clients/$clientId/edit': typeof AdminClientsClientIdEditRoute
  '/clients/$clientId/pdf': typeof AdminClientsClientIdPdfRoute
  '/clients/$clientId/view': typeof AdminClientsClientIdViewRoute
  '/clients/data/$clientId': typeof AdminClientsDataClientIdRoute
  '/drivers/$driverId/edit': typeof AdminDriversDriverIdEditRoute
  '/drivers/$driverId/view': typeof AdminDriversDriverIdViewRoute
  '/rides/$rideId/edit': typeof AdminRidesRideIdEditRoute
  '/rides/$rideId/view': typeof AdminRidesRideIdViewRoute
  '/services/$serviceId/edit': typeof AdminServicesServiceIdEditRoute
  '/services/$serviceId/view': typeof AdminServicesServiceIdViewRoute
  '/vehicles/$vehicleId/edit': typeof AdminVehiclesVehicleIdEditRoute
  '/vehicles/$vehicleId/view': typeof AdminVehiclesVehicleIdViewRoute
  '/bookings/new': typeof AdminBookingsNewIndexRoute
  '/clients/new': typeof AdminClientsNewIndexRoute
  '/reports/audits': typeof AdminReportsAuditsIndexRoute
  '/services/new': typeof AdminServicesNewIndexRoute
  '/settings/advanced': typeof AdminSettingsAdvancedIndexRoute
  '/settings/booking-routes': typeof AdminSettingsBookingRoutesIndexRoute
  '/settings/company-details': typeof AdminSettingsCompanyDetailsIndexRoute
  '/settings/generate-numbers': typeof AdminSettingsGenerateNumbersIndexRoute
  '/settings/notifications': typeof AdminSettingsNotificationsIndexRoute
  '/settings/pdf-templates': typeof AdminSettingsPdfTemplatesIndexRoute
  '/settings/pricing-config': typeof AdminSettingsPricingConfigIndexRoute
  '/settings/tax-rates': typeof AdminSettingsTaxRatesIndexRoute
  '/vehicles/new': typeof AdminVehiclesNewIndexRoute
  '/settings/user-management/permissions': typeof AdminSettingsUserManagementPermissionsIndexRoute
  '/settings/user-management/roles': typeof AdminSettingsUserManagementRolesIndexRoute
  '/settings/user-management/users': typeof AdminSettingsUserManagementUsersIndexRoute
  '/settings/vehicle-config/car-brands': typeof AdminSettingsVehicleConfigCarBrandsIndexRoute
  '/settings/vehicle-config/car-models': typeof AdminSettingsVehicleConfigCarModelsIndexRoute
  '/settings/vehicle-config/drive-trains': typeof AdminSettingsVehicleConfigDriveTrainsIndexRoute
  '/settings/vehicle-config/tonnages': typeof AdminSettingsVehicleConfigTonnagesIndexRoute
  '/settings/vehicle-config/vehicle-types': typeof AdminSettingsVehicleConfigVehicleTypesIndexRoute
  '/settings/user-management/users/$userId/edit': typeof AdminSettingsUserManagementUsersUserIdEditRoute
  '/settings/user-management/users/$userId/view': typeof AdminSettingsUserManagementUsersUserIdViewRoute
  '/settings/user-management/users/new': typeof AdminSettingsUserManagementUsersNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_admin/settings': typeof AdminSettingsRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/logout': typeof AuthLogoutRoute
  '/_auth/unauthorized': typeof AuthUnauthorizedRoute
  '/_auth/unauthorized-module': typeof AuthUnauthorizedModuleRoute
  '/_admin/settings/user-management': typeof AdminSettingsUserManagementRouteRouteWithChildren
  '/_admin/settings/vehicle-config': typeof AdminSettingsVehicleConfigRouteRouteWithChildren
  '/_admin/clients/pricing': typeof AdminClientsPricingRoute
  '/_admin/clients/pricing-rates': typeof AdminClientsPricingRatesRoute
  '/_admin/clients/rates': typeof AdminClientsRatesRoute
  '/_admin/drivers/new': typeof AdminDriversNewRoute
  '/_admin/rides/live': typeof AdminRidesLiveRoute
  '/_admin/rides/new': typeof AdminRidesNewRoute
  '/_admin/bookings/': typeof AdminBookingsIndexRoute
  '/_admin/clients/': typeof AdminClientsIndexRoute
  '/_admin/dashboard/': typeof AdminDashboardIndexRoute
  '/_admin/drivers/': typeof AdminDriversIndexRoute
  '/_admin/payments/': typeof AdminPaymentsIndexRoute
  '/_admin/reports/': typeof AdminReportsIndexRoute
  '/_admin/reviews/': typeof AdminReviewsIndexRoute
  '/_admin/rides/': typeof AdminRidesIndexRoute
  '/_admin/services/': typeof AdminServicesIndexRoute
  '/_admin/vehicles/': typeof AdminVehiclesIndexRoute
  '/_admin/bookings/$bookingId/edit': typeof AdminBookingsBookingIdEditRoute
  '/_admin/bookings/$bookingId/view': typeof AdminBookingsBookingIdViewRoute
  '/_admin/clients/$clientId/edit': typeof AdminClientsClientIdEditRoute
  '/_admin/clients/$clientId/pdf': typeof AdminClientsClientIdPdfRoute
  '/_admin/clients/$clientId/view': typeof AdminClientsClientIdViewRoute
  '/_admin/clients/data/$clientId': typeof AdminClientsDataClientIdRoute
  '/_admin/drivers/$driverId/edit': typeof AdminDriversDriverIdEditRoute
  '/_admin/drivers/$driverId/view': typeof AdminDriversDriverIdViewRoute
  '/_admin/rides/$rideId/edit': typeof AdminRidesRideIdEditRoute
  '/_admin/rides/$rideId/view': typeof AdminRidesRideIdViewRoute
  '/_admin/services/$serviceId/edit': typeof AdminServicesServiceIdEditRoute
  '/_admin/services/$serviceId/view': typeof AdminServicesServiceIdViewRoute
  '/_admin/vehicles/$vehicleId/edit': typeof AdminVehiclesVehicleIdEditRoute
  '/_admin/vehicles/$vehicleId/view': typeof AdminVehiclesVehicleIdViewRoute
  '/_admin/bookings/new/': typeof AdminBookingsNewIndexRoute
  '/_admin/clients/new/': typeof AdminClientsNewIndexRoute
  '/_admin/reports/audits/': typeof AdminReportsAuditsIndexRoute
  '/_admin/services/new/': typeof AdminServicesNewIndexRoute
  '/_admin/settings/advanced/': typeof AdminSettingsAdvancedIndexRoute
  '/_admin/settings/booking-routes/': typeof AdminSettingsBookingRoutesIndexRoute
  '/_admin/settings/company-details/': typeof AdminSettingsCompanyDetailsIndexRoute
  '/_admin/settings/generate-numbers/': typeof AdminSettingsGenerateNumbersIndexRoute
  '/_admin/settings/notifications/': typeof AdminSettingsNotificationsIndexRoute
  '/_admin/settings/pdf-templates/': typeof AdminSettingsPdfTemplatesIndexRoute
  '/_admin/settings/pricing-config/': typeof AdminSettingsPricingConfigIndexRoute
  '/_admin/settings/tax-rates/': typeof AdminSettingsTaxRatesIndexRoute
  '/_admin/vehicles/new/': typeof AdminVehiclesNewIndexRoute
  '/_admin/settings/user-management/permissions/': typeof AdminSettingsUserManagementPermissionsIndexRoute
  '/_admin/settings/user-management/roles/': typeof AdminSettingsUserManagementRolesIndexRoute
  '/_admin/settings/user-management/users/': typeof AdminSettingsUserManagementUsersIndexRoute
  '/_admin/settings/vehicle-config/car-brands/': typeof AdminSettingsVehicleConfigCarBrandsIndexRoute
  '/_admin/settings/vehicle-config/car-models/': typeof AdminSettingsVehicleConfigCarModelsIndexRoute
  '/_admin/settings/vehicle-config/drive-trains/': typeof AdminSettingsVehicleConfigDriveTrainsIndexRoute
  '/_admin/settings/vehicle-config/tonnages/': typeof AdminSettingsVehicleConfigTonnagesIndexRoute
  '/_admin/settings/vehicle-config/vehicle-types/': typeof AdminSettingsVehicleConfigVehicleTypesIndexRoute
  '/_admin/settings/user-management/users/$userId/edit': typeof AdminSettingsUserManagementUsersUserIdEditRoute
  '/_admin/settings/user-management/users/$userId/view': typeof AdminSettingsUserManagementUsersUserIdViewRoute
  '/_admin/settings/user-management/users/new/': typeof AdminSettingsUserManagementUsersNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/login'
    | '/logout'
    | '/unauthorized'
    | '/unauthorized-module'
    | '/settings/user-management'
    | '/settings/vehicle-config'
    | '/clients/pricing'
    | '/clients/pricing-rates'
    | '/clients/rates'
    | '/drivers/new'
    | '/rides/live'
    | '/rides/new'
    | '/bookings/'
    | '/clients/'
    | '/dashboard/'
    | '/drivers/'
    | '/payments/'
    | '/reports/'
    | '/reviews/'
    | '/rides/'
    | '/services/'
    | '/vehicles/'
    | '/bookings/$bookingId/edit'
    | '/bookings/$bookingId/view'
    | '/clients/$clientId/edit'
    | '/clients/$clientId/pdf'
    | '/clients/$clientId/view'
    | '/clients/data/$clientId'
    | '/drivers/$driverId/edit'
    | '/drivers/$driverId/view'
    | '/rides/$rideId/edit'
    | '/rides/$rideId/view'
    | '/services/$serviceId/edit'
    | '/services/$serviceId/view'
    | '/vehicles/$vehicleId/edit'
    | '/vehicles/$vehicleId/view'
    | '/bookings/new/'
    | '/clients/new/'
    | '/reports/audits/'
    | '/services/new/'
    | '/settings/advanced/'
    | '/settings/booking-routes/'
    | '/settings/company-details/'
    | '/settings/generate-numbers/'
    | '/settings/notifications/'
    | '/settings/pdf-templates/'
    | '/settings/pricing-config/'
    | '/settings/tax-rates/'
    | '/vehicles/new/'
    | '/settings/user-management/permissions/'
    | '/settings/user-management/roles/'
    | '/settings/user-management/users/'
    | '/settings/vehicle-config/car-brands/'
    | '/settings/vehicle-config/car-models/'
    | '/settings/vehicle-config/drive-trains/'
    | '/settings/vehicle-config/tonnages/'
    | '/settings/vehicle-config/vehicle-types/'
    | '/settings/user-management/users/$userId/edit'
    | '/settings/user-management/users/$userId/view'
    | '/settings/user-management/users/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/login'
    | '/logout'
    | '/unauthorized'
    | '/unauthorized-module'
    | '/settings/user-management'
    | '/settings/vehicle-config'
    | '/clients/pricing'
    | '/clients/pricing-rates'
    | '/clients/rates'
    | '/drivers/new'
    | '/rides/live'
    | '/rides/new'
    | '/bookings'
    | '/clients'
    | '/dashboard'
    | '/drivers'
    | '/payments'
    | '/reports'
    | '/reviews'
    | '/rides'
    | '/services'
    | '/vehicles'
    | '/bookings/$bookingId/edit'
    | '/bookings/$bookingId/view'
    | '/clients/$clientId/edit'
    | '/clients/$clientId/pdf'
    | '/clients/$clientId/view'
    | '/clients/data/$clientId'
    | '/drivers/$driverId/edit'
    | '/drivers/$driverId/view'
    | '/rides/$rideId/edit'
    | '/rides/$rideId/view'
    | '/services/$serviceId/edit'
    | '/services/$serviceId/view'
    | '/vehicles/$vehicleId/edit'
    | '/vehicles/$vehicleId/view'
    | '/bookings/new'
    | '/clients/new'
    | '/reports/audits'
    | '/services/new'
    | '/settings/advanced'
    | '/settings/booking-routes'
    | '/settings/company-details'
    | '/settings/generate-numbers'
    | '/settings/notifications'
    | '/settings/pdf-templates'
    | '/settings/pricing-config'
    | '/settings/tax-rates'
    | '/vehicles/new'
    | '/settings/user-management/permissions'
    | '/settings/user-management/roles'
    | '/settings/user-management/users'
    | '/settings/vehicle-config/car-brands'
    | '/settings/vehicle-config/car-models'
    | '/settings/vehicle-config/drive-trains'
    | '/settings/vehicle-config/tonnages'
    | '/settings/vehicle-config/vehicle-types'
    | '/settings/user-management/users/$userId/edit'
    | '/settings/user-management/users/$userId/view'
    | '/settings/user-management/users/new'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_admin/settings'
    | '/_auth/login'
    | '/_auth/logout'
    | '/_auth/unauthorized'
    | '/_auth/unauthorized-module'
    | '/_admin/settings/user-management'
    | '/_admin/settings/vehicle-config'
    | '/_admin/clients/pricing'
    | '/_admin/clients/pricing-rates'
    | '/_admin/clients/rates'
    | '/_admin/drivers/new'
    | '/_admin/rides/live'
    | '/_admin/rides/new'
    | '/_admin/bookings/'
    | '/_admin/clients/'
    | '/_admin/dashboard/'
    | '/_admin/drivers/'
    | '/_admin/payments/'
    | '/_admin/reports/'
    | '/_admin/reviews/'
    | '/_admin/rides/'
    | '/_admin/services/'
    | '/_admin/vehicles/'
    | '/_admin/bookings/$bookingId/edit'
    | '/_admin/bookings/$bookingId/view'
    | '/_admin/clients/$clientId/edit'
    | '/_admin/clients/$clientId/pdf'
    | '/_admin/clients/$clientId/view'
    | '/_admin/clients/data/$clientId'
    | '/_admin/drivers/$driverId/edit'
    | '/_admin/drivers/$driverId/view'
    | '/_admin/rides/$rideId/edit'
    | '/_admin/rides/$rideId/view'
    | '/_admin/services/$serviceId/edit'
    | '/_admin/services/$serviceId/view'
    | '/_admin/vehicles/$vehicleId/edit'
    | '/_admin/vehicles/$vehicleId/view'
    | '/_admin/bookings/new/'
    | '/_admin/clients/new/'
    | '/_admin/reports/audits/'
    | '/_admin/services/new/'
    | '/_admin/settings/advanced/'
    | '/_admin/settings/booking-routes/'
    | '/_admin/settings/company-details/'
    | '/_admin/settings/generate-numbers/'
    | '/_admin/settings/notifications/'
    | '/_admin/settings/pdf-templates/'
    | '/_admin/settings/pricing-config/'
    | '/_admin/settings/tax-rates/'
    | '/_admin/vehicles/new/'
    | '/_admin/settings/user-management/permissions/'
    | '/_admin/settings/user-management/roles/'
    | '/_admin/settings/user-management/users/'
    | '/_admin/settings/vehicle-config/car-brands/'
    | '/_admin/settings/vehicle-config/car-models/'
    | '/_admin/settings/vehicle-config/drive-trains/'
    | '/_admin/settings/vehicle-config/tonnages/'
    | '/_admin/settings/vehicle-config/vehicle-types/'
    | '/_admin/settings/user-management/users/$userId/edit'
    | '/_admin/settings/user-management/users/$userId/view'
    | '/_admin/settings/user-management/users/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthUnauthorizedRoute: typeof AuthUnauthorizedRoute
  AuthUnauthorizedModuleRoute: typeof AuthUnauthorizedModuleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/unauthorized-module': {
      id: '/_auth/unauthorized-module'
      path: '/unauthorized-module'
      fullPath: '/unauthorized-module'
      preLoaderRoute: typeof AuthUnauthorizedModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/unauthorized': {
      id: '/_auth/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof AuthUnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/logout': {
      id: '/_auth/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/vehicles/': {
      id: '/_admin/vehicles/'
      path: '/vehicles'
      fullPath: '/vehicles/'
      preLoaderRoute: typeof AdminVehiclesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/services/': {
      id: '/_admin/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof AdminServicesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/rides/': {
      id: '/_admin/rides/'
      path: '/rides'
      fullPath: '/rides/'
      preLoaderRoute: typeof AdminRidesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/reviews/': {
      id: '/_admin/reviews/'
      path: '/reviews'
      fullPath: '/reviews/'
      preLoaderRoute: typeof AdminReviewsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/reports/': {
      id: '/_admin/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AdminReportsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/payments/': {
      id: '/_admin/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof AdminPaymentsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/drivers/': {
      id: '/_admin/drivers/'
      path: '/drivers'
      fullPath: '/drivers/'
      preLoaderRoute: typeof AdminDriversIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/dashboard/': {
      id: '/_admin/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/clients/': {
      id: '/_admin/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AdminClientsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/bookings/': {
      id: '/_admin/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof AdminBookingsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/rides/new': {
      id: '/_admin/rides/new'
      path: '/rides/new'
      fullPath: '/rides/new'
      preLoaderRoute: typeof AdminRidesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/rides/live': {
      id: '/_admin/rides/live'
      path: '/rides/live'
      fullPath: '/rides/live'
      preLoaderRoute: typeof AdminRidesLiveRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/drivers/new': {
      id: '/_admin/drivers/new'
      path: '/drivers/new'
      fullPath: '/drivers/new'
      preLoaderRoute: typeof AdminDriversNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/clients/rates': {
      id: '/_admin/clients/rates'
      path: '/clients/rates'
      fullPath: '/clients/rates'
      preLoaderRoute: typeof AdminClientsRatesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/clients/pricing-rates': {
      id: '/_admin/clients/pricing-rates'
      path: '/clients/pricing-rates'
      fullPath: '/clients/pricing-rates'
      preLoaderRoute: typeof AdminClientsPricingRatesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/clients/pricing': {
      id: '/_admin/clients/pricing'
      path: '/clients/pricing'
      fullPath: '/clients/pricing'
      preLoaderRoute: typeof AdminClientsPricingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/settings/vehicle-config': {
      id: '/_admin/settings/vehicle-config'
      path: '/vehicle-config'
      fullPath: '/settings/vehicle-config'
      preLoaderRoute: typeof AdminSettingsVehicleConfigRouteRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/_admin/settings/user-management': {
      id: '/_admin/settings/user-management'
      path: '/user-management'
      fullPath: '/settings/user-management'
      preLoaderRoute: typeof AdminSettingsUserManagementRouteRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/_admin/vehicles/new/': {
      id: '/_admin/vehicles/new/'
      path: '/vehicles/new'
      fullPath: '/vehicles/new/'
      preLoaderRoute: typeof AdminVehiclesNewIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/settings/tax-rates/': {
      id: '/_admin/settings/tax-rates/'
      path: '/tax-rates'
      fullPath: '/settings/tax-rates/'
      preLoaderRoute: typeof AdminSettingsTaxRatesIndexRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/_admin/settings/pricing-config/': {
      id: '/_admin/settings/pricing-config/'
      path: '/pricing-config'
      fullPath: '/settings/pricing-config/'
      preLoaderRoute: typeof AdminSettingsPricingConfigIndexRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/_admin/settings/pdf-templates/': {
      id: '/_admin/settings/pdf-templates/'
      path: '/pdf-templates'
      fullPath: '/settings/pdf-templates/'
      preLoaderRoute: typeof AdminSettingsPdfTemplatesIndexRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/_admin/settings/notifications/': {
      id: '/_admin/settings/notifications/'
      path: '/notifications'
      fullPath: '/settings/notifications/'
      preLoaderRoute: typeof AdminSettingsNotificationsIndexRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/_admin/settings/generate-numbers/': {
      id: '/_admin/settings/generate-numbers/'
      path: '/generate-numbers'
      fullPath: '/settings/generate-numbers/'
      preLoaderRoute: typeof AdminSettingsGenerateNumbersIndexRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/_admin/settings/company-details/': {
      id: '/_admin/settings/company-details/'
      path: '/company-details'
      fullPath: '/settings/company-details/'
      preLoaderRoute: typeof AdminSettingsCompanyDetailsIndexRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/_admin/settings/booking-routes/': {
      id: '/_admin/settings/booking-routes/'
      path: '/booking-routes'
      fullPath: '/settings/booking-routes/'
      preLoaderRoute: typeof AdminSettingsBookingRoutesIndexRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/_admin/settings/advanced/': {
      id: '/_admin/settings/advanced/'
      path: '/advanced'
      fullPath: '/settings/advanced/'
      preLoaderRoute: typeof AdminSettingsAdvancedIndexRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/_admin/services/new/': {
      id: '/_admin/services/new/'
      path: '/services/new'
      fullPath: '/services/new/'
      preLoaderRoute: typeof AdminServicesNewIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/reports/audits/': {
      id: '/_admin/reports/audits/'
      path: '/reports/audits'
      fullPath: '/reports/audits/'
      preLoaderRoute: typeof AdminReportsAuditsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/clients/new/': {
      id: '/_admin/clients/new/'
      path: '/clients/new'
      fullPath: '/clients/new/'
      preLoaderRoute: typeof AdminClientsNewIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/bookings/new/': {
      id: '/_admin/bookings/new/'
      path: '/bookings/new'
      fullPath: '/bookings/new/'
      preLoaderRoute: typeof AdminBookingsNewIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/vehicles/$vehicleId/view': {
      id: '/_admin/vehicles/$vehicleId/view'
      path: '/vehicles/$vehicleId/view'
      fullPath: '/vehicles/$vehicleId/view'
      preLoaderRoute: typeof AdminVehiclesVehicleIdViewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/vehicles/$vehicleId/edit': {
      id: '/_admin/vehicles/$vehicleId/edit'
      path: '/vehicles/$vehicleId/edit'
      fullPath: '/vehicles/$vehicleId/edit'
      preLoaderRoute: typeof AdminVehiclesVehicleIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/services/$serviceId/view': {
      id: '/_admin/services/$serviceId/view'
      path: '/services/$serviceId/view'
      fullPath: '/services/$serviceId/view'
      preLoaderRoute: typeof AdminServicesServiceIdViewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/services/$serviceId/edit': {
      id: '/_admin/services/$serviceId/edit'
      path: '/services/$serviceId/edit'
      fullPath: '/services/$serviceId/edit'
      preLoaderRoute: typeof AdminServicesServiceIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/rides/$rideId/view': {
      id: '/_admin/rides/$rideId/view'
      path: '/rides/$rideId/view'
      fullPath: '/rides/$rideId/view'
      preLoaderRoute: typeof AdminRidesRideIdViewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/rides/$rideId/edit': {
      id: '/_admin/rides/$rideId/edit'
      path: '/rides/$rideId/edit'
      fullPath: '/rides/$rideId/edit'
      preLoaderRoute: typeof AdminRidesRideIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/drivers/$driverId/view': {
      id: '/_admin/drivers/$driverId/view'
      path: '/drivers/$driverId/view'
      fullPath: '/drivers/$driverId/view'
      preLoaderRoute: typeof AdminDriversDriverIdViewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/drivers/$driverId/edit': {
      id: '/_admin/drivers/$driverId/edit'
      path: '/drivers/$driverId/edit'
      fullPath: '/drivers/$driverId/edit'
      preLoaderRoute: typeof AdminDriversDriverIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/clients/data/$clientId': {
      id: '/_admin/clients/data/$clientId'
      path: '/clients/data/$clientId'
      fullPath: '/clients/data/$clientId'
      preLoaderRoute: typeof AdminClientsDataClientIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/clients/$clientId/view': {
      id: '/_admin/clients/$clientId/view'
      path: '/clients/$clientId/view'
      fullPath: '/clients/$clientId/view'
      preLoaderRoute: typeof AdminClientsClientIdViewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/clients/$clientId/pdf': {
      id: '/_admin/clients/$clientId/pdf'
      path: '/clients/$clientId/pdf'
      fullPath: '/clients/$clientId/pdf'
      preLoaderRoute: typeof AdminClientsClientIdPdfRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/clients/$clientId/edit': {
      id: '/_admin/clients/$clientId/edit'
      path: '/clients/$clientId/edit'
      fullPath: '/clients/$clientId/edit'
      preLoaderRoute: typeof AdminClientsClientIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/bookings/$bookingId/view': {
      id: '/_admin/bookings/$bookingId/view'
      path: '/bookings/$bookingId/view'
      fullPath: '/bookings/$bookingId/view'
      preLoaderRoute: typeof AdminBookingsBookingIdViewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/bookings/$bookingId/edit': {
      id: '/_admin/bookings/$bookingId/edit'
      path: '/bookings/$bookingId/edit'
      fullPath: '/bookings/$bookingId/edit'
      preLoaderRoute: typeof AdminBookingsBookingIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/settings/vehicle-config/vehicle-types/': {
      id: '/_admin/settings/vehicle-config/vehicle-types/'
      path: '/vehicle-types'
      fullPath: '/settings/vehicle-config/vehicle-types/'
      preLoaderRoute: typeof AdminSettingsVehicleConfigVehicleTypesIndexRouteImport
      parentRoute: typeof AdminSettingsVehicleConfigRouteRoute
    }
    '/_admin/settings/vehicle-config/tonnages/': {
      id: '/_admin/settings/vehicle-config/tonnages/'
      path: '/tonnages'
      fullPath: '/settings/vehicle-config/tonnages/'
      preLoaderRoute: typeof AdminSettingsVehicleConfigTonnagesIndexRouteImport
      parentRoute: typeof AdminSettingsVehicleConfigRouteRoute
    }
    '/_admin/settings/vehicle-config/drive-trains/': {
      id: '/_admin/settings/vehicle-config/drive-trains/'
      path: '/drive-trains'
      fullPath: '/settings/vehicle-config/drive-trains/'
      preLoaderRoute: typeof AdminSettingsVehicleConfigDriveTrainsIndexRouteImport
      parentRoute: typeof AdminSettingsVehicleConfigRouteRoute
    }
    '/_admin/settings/vehicle-config/car-models/': {
      id: '/_admin/settings/vehicle-config/car-models/'
      path: '/car-models'
      fullPath: '/settings/vehicle-config/car-models/'
      preLoaderRoute: typeof AdminSettingsVehicleConfigCarModelsIndexRouteImport
      parentRoute: typeof AdminSettingsVehicleConfigRouteRoute
    }
    '/_admin/settings/vehicle-config/car-brands/': {
      id: '/_admin/settings/vehicle-config/car-brands/'
      path: '/car-brands'
      fullPath: '/settings/vehicle-config/car-brands/'
      preLoaderRoute: typeof AdminSettingsVehicleConfigCarBrandsIndexRouteImport
      parentRoute: typeof AdminSettingsVehicleConfigRouteRoute
    }
    '/_admin/settings/user-management/users/': {
      id: '/_admin/settings/user-management/users/'
      path: '/users'
      fullPath: '/settings/user-management/users/'
      preLoaderRoute: typeof AdminSettingsUserManagementUsersIndexRouteImport
      parentRoute: typeof AdminSettingsUserManagementRouteRoute
    }
    '/_admin/settings/user-management/roles/': {
      id: '/_admin/settings/user-management/roles/'
      path: '/roles'
      fullPath: '/settings/user-management/roles/'
      preLoaderRoute: typeof AdminSettingsUserManagementRolesIndexRouteImport
      parentRoute: typeof AdminSettingsUserManagementRouteRoute
    }
    '/_admin/settings/user-management/permissions/': {
      id: '/_admin/settings/user-management/permissions/'
      path: '/permissions'
      fullPath: '/settings/user-management/permissions/'
      preLoaderRoute: typeof AdminSettingsUserManagementPermissionsIndexRouteImport
      parentRoute: typeof AdminSettingsUserManagementRouteRoute
    }
    '/_admin/settings/user-management/users/new/': {
      id: '/_admin/settings/user-management/users/new/'
      path: '/users/new'
      fullPath: '/settings/user-management/users/new/'
      preLoaderRoute: typeof AdminSettingsUserManagementUsersNewIndexRouteImport
      parentRoute: typeof AdminSettingsUserManagementRouteRoute
    }
    '/_admin/settings/user-management/users/$userId/view': {
      id: '/_admin/settings/user-management/users/$userId/view'
      path: '/users/$userId/view'
      fullPath: '/settings/user-management/users/$userId/view'
      preLoaderRoute: typeof AdminSettingsUserManagementUsersUserIdViewRouteImport
      parentRoute: typeof AdminSettingsUserManagementRouteRoute
    }
    '/_admin/settings/user-management/users/$userId/edit': {
      id: '/_admin/settings/user-management/users/$userId/edit'
      path: '/users/$userId/edit'
      fullPath: '/settings/user-management/users/$userId/edit'
      preLoaderRoute: typeof AdminSettingsUserManagementUsersUserIdEditRouteImport
      parentRoute: typeof AdminSettingsUserManagementRouteRoute
    }
  }
}

interface AdminSettingsUserManagementRouteRouteChildren {
  AdminSettingsUserManagementPermissionsIndexRoute: typeof AdminSettingsUserManagementPermissionsIndexRoute
  AdminSettingsUserManagementRolesIndexRoute: typeof AdminSettingsUserManagementRolesIndexRoute
  AdminSettingsUserManagementUsersIndexRoute: typeof AdminSettingsUserManagementUsersIndexRoute
  AdminSettingsUserManagementUsersUserIdEditRoute: typeof AdminSettingsUserManagementUsersUserIdEditRoute
  AdminSettingsUserManagementUsersUserIdViewRoute: typeof AdminSettingsUserManagementUsersUserIdViewRoute
  AdminSettingsUserManagementUsersNewIndexRoute: typeof AdminSettingsUserManagementUsersNewIndexRoute
}

const AdminSettingsUserManagementRouteRouteChildren: AdminSettingsUserManagementRouteRouteChildren =
  {
    AdminSettingsUserManagementPermissionsIndexRoute:
      AdminSettingsUserManagementPermissionsIndexRoute,
    AdminSettingsUserManagementRolesIndexRoute:
      AdminSettingsUserManagementRolesIndexRoute,
    AdminSettingsUserManagementUsersIndexRoute:
      AdminSettingsUserManagementUsersIndexRoute,
    AdminSettingsUserManagementUsersUserIdEditRoute:
      AdminSettingsUserManagementUsersUserIdEditRoute,
    AdminSettingsUserManagementUsersUserIdViewRoute:
      AdminSettingsUserManagementUsersUserIdViewRoute,
    AdminSettingsUserManagementUsersNewIndexRoute:
      AdminSettingsUserManagementUsersNewIndexRoute,
  }

const AdminSettingsUserManagementRouteRouteWithChildren =
  AdminSettingsUserManagementRouteRoute._addFileChildren(
    AdminSettingsUserManagementRouteRouteChildren,
  )

interface AdminSettingsVehicleConfigRouteRouteChildren {
  AdminSettingsVehicleConfigCarBrandsIndexRoute: typeof AdminSettingsVehicleConfigCarBrandsIndexRoute
  AdminSettingsVehicleConfigCarModelsIndexRoute: typeof AdminSettingsVehicleConfigCarModelsIndexRoute
  AdminSettingsVehicleConfigDriveTrainsIndexRoute: typeof AdminSettingsVehicleConfigDriveTrainsIndexRoute
  AdminSettingsVehicleConfigTonnagesIndexRoute: typeof AdminSettingsVehicleConfigTonnagesIndexRoute
  AdminSettingsVehicleConfigVehicleTypesIndexRoute: typeof AdminSettingsVehicleConfigVehicleTypesIndexRoute
}

const AdminSettingsVehicleConfigRouteRouteChildren: AdminSettingsVehicleConfigRouteRouteChildren =
  {
    AdminSettingsVehicleConfigCarBrandsIndexRoute:
      AdminSettingsVehicleConfigCarBrandsIndexRoute,
    AdminSettingsVehicleConfigCarModelsIndexRoute:
      AdminSettingsVehicleConfigCarModelsIndexRoute,
    AdminSettingsVehicleConfigDriveTrainsIndexRoute:
      AdminSettingsVehicleConfigDriveTrainsIndexRoute,
    AdminSettingsVehicleConfigTonnagesIndexRoute:
      AdminSettingsVehicleConfigTonnagesIndexRoute,
    AdminSettingsVehicleConfigVehicleTypesIndexRoute:
      AdminSettingsVehicleConfigVehicleTypesIndexRoute,
  }

const AdminSettingsVehicleConfigRouteRouteWithChildren =
  AdminSettingsVehicleConfigRouteRoute._addFileChildren(
    AdminSettingsVehicleConfigRouteRouteChildren,
  )

interface AdminSettingsRouteRouteChildren {
  AdminSettingsUserManagementRouteRoute: typeof AdminSettingsUserManagementRouteRouteWithChildren
  AdminSettingsVehicleConfigRouteRoute: typeof AdminSettingsVehicleConfigRouteRouteWithChildren
  AdminSettingsAdvancedIndexRoute: typeof AdminSettingsAdvancedIndexRoute
  AdminSettingsBookingRoutesIndexRoute: typeof AdminSettingsBookingRoutesIndexRoute
  AdminSettingsCompanyDetailsIndexRoute: typeof AdminSettingsCompanyDetailsIndexRoute
  AdminSettingsGenerateNumbersIndexRoute: typeof AdminSettingsGenerateNumbersIndexRoute
  AdminSettingsNotificationsIndexRoute: typeof AdminSettingsNotificationsIndexRoute
  AdminSettingsPdfTemplatesIndexRoute: typeof AdminSettingsPdfTemplatesIndexRoute
  AdminSettingsPricingConfigIndexRoute: typeof AdminSettingsPricingConfigIndexRoute
  AdminSettingsTaxRatesIndexRoute: typeof AdminSettingsTaxRatesIndexRoute
}

const AdminSettingsRouteRouteChildren: AdminSettingsRouteRouteChildren = {
  AdminSettingsUserManagementRouteRoute:
    AdminSettingsUserManagementRouteRouteWithChildren,
  AdminSettingsVehicleConfigRouteRoute:
    AdminSettingsVehicleConfigRouteRouteWithChildren,
  AdminSettingsAdvancedIndexRoute: AdminSettingsAdvancedIndexRoute,
  AdminSettingsBookingRoutesIndexRoute: AdminSettingsBookingRoutesIndexRoute,
  AdminSettingsCompanyDetailsIndexRoute: AdminSettingsCompanyDetailsIndexRoute,
  AdminSettingsGenerateNumbersIndexRoute:
    AdminSettingsGenerateNumbersIndexRoute,
  AdminSettingsNotificationsIndexRoute: AdminSettingsNotificationsIndexRoute,
  AdminSettingsPdfTemplatesIndexRoute: AdminSettingsPdfTemplatesIndexRoute,
  AdminSettingsPricingConfigIndexRoute: AdminSettingsPricingConfigIndexRoute,
  AdminSettingsTaxRatesIndexRoute: AdminSettingsTaxRatesIndexRoute,
}

const AdminSettingsRouteRouteWithChildren =
  AdminSettingsRouteRoute._addFileChildren(AdminSettingsRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminSettingsRouteRoute: typeof AdminSettingsRouteRouteWithChildren
  AdminClientsPricingRoute: typeof AdminClientsPricingRoute
  AdminClientsPricingRatesRoute: typeof AdminClientsPricingRatesRoute
  AdminClientsRatesRoute: typeof AdminClientsRatesRoute
  AdminDriversNewRoute: typeof AdminDriversNewRoute
  AdminRidesLiveRoute: typeof AdminRidesLiveRoute
  AdminRidesNewRoute: typeof AdminRidesNewRoute
  AdminBookingsIndexRoute: typeof AdminBookingsIndexRoute
  AdminClientsIndexRoute: typeof AdminClientsIndexRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminDriversIndexRoute: typeof AdminDriversIndexRoute
  AdminPaymentsIndexRoute: typeof AdminPaymentsIndexRoute
  AdminReportsIndexRoute: typeof AdminReportsIndexRoute
  AdminReviewsIndexRoute: typeof AdminReviewsIndexRoute
  AdminRidesIndexRoute: typeof AdminRidesIndexRoute
  AdminServicesIndexRoute: typeof AdminServicesIndexRoute
  AdminVehiclesIndexRoute: typeof AdminVehiclesIndexRoute
  AdminBookingsBookingIdEditRoute: typeof AdminBookingsBookingIdEditRoute
  AdminBookingsBookingIdViewRoute: typeof AdminBookingsBookingIdViewRoute
  AdminClientsClientIdEditRoute: typeof AdminClientsClientIdEditRoute
  AdminClientsClientIdPdfRoute: typeof AdminClientsClientIdPdfRoute
  AdminClientsClientIdViewRoute: typeof AdminClientsClientIdViewRoute
  AdminClientsDataClientIdRoute: typeof AdminClientsDataClientIdRoute
  AdminDriversDriverIdEditRoute: typeof AdminDriversDriverIdEditRoute
  AdminDriversDriverIdViewRoute: typeof AdminDriversDriverIdViewRoute
  AdminRidesRideIdEditRoute: typeof AdminRidesRideIdEditRoute
  AdminRidesRideIdViewRoute: typeof AdminRidesRideIdViewRoute
  AdminServicesServiceIdEditRoute: typeof AdminServicesServiceIdEditRoute
  AdminServicesServiceIdViewRoute: typeof AdminServicesServiceIdViewRoute
  AdminVehiclesVehicleIdEditRoute: typeof AdminVehiclesVehicleIdEditRoute
  AdminVehiclesVehicleIdViewRoute: typeof AdminVehiclesVehicleIdViewRoute
  AdminBookingsNewIndexRoute: typeof AdminBookingsNewIndexRoute
  AdminClientsNewIndexRoute: typeof AdminClientsNewIndexRoute
  AdminReportsAuditsIndexRoute: typeof AdminReportsAuditsIndexRoute
  AdminServicesNewIndexRoute: typeof AdminServicesNewIndexRoute
  AdminVehiclesNewIndexRoute: typeof AdminVehiclesNewIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminSettingsRouteRoute: AdminSettingsRouteRouteWithChildren,
  AdminClientsPricingRoute: AdminClientsPricingRoute,
  AdminClientsPricingRatesRoute: AdminClientsPricingRatesRoute,
  AdminClientsRatesRoute: AdminClientsRatesRoute,
  AdminDriversNewRoute: AdminDriversNewRoute,
  AdminRidesLiveRoute: AdminRidesLiveRoute,
  AdminRidesNewRoute: AdminRidesNewRoute,
  AdminBookingsIndexRoute: AdminBookingsIndexRoute,
  AdminClientsIndexRoute: AdminClientsIndexRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminDriversIndexRoute: AdminDriversIndexRoute,
  AdminPaymentsIndexRoute: AdminPaymentsIndexRoute,
  AdminReportsIndexRoute: AdminReportsIndexRoute,
  AdminReviewsIndexRoute: AdminReviewsIndexRoute,
  AdminRidesIndexRoute: AdminRidesIndexRoute,
  AdminServicesIndexRoute: AdminServicesIndexRoute,
  AdminVehiclesIndexRoute: AdminVehiclesIndexRoute,
  AdminBookingsBookingIdEditRoute: AdminBookingsBookingIdEditRoute,
  AdminBookingsBookingIdViewRoute: AdminBookingsBookingIdViewRoute,
  AdminClientsClientIdEditRoute: AdminClientsClientIdEditRoute,
  AdminClientsClientIdPdfRoute: AdminClientsClientIdPdfRoute,
  AdminClientsClientIdViewRoute: AdminClientsClientIdViewRoute,
  AdminClientsDataClientIdRoute: AdminClientsDataClientIdRoute,
  AdminDriversDriverIdEditRoute: AdminDriversDriverIdEditRoute,
  AdminDriversDriverIdViewRoute: AdminDriversDriverIdViewRoute,
  AdminRidesRideIdEditRoute: AdminRidesRideIdEditRoute,
  AdminRidesRideIdViewRoute: AdminRidesRideIdViewRoute,
  AdminServicesServiceIdEditRoute: AdminServicesServiceIdEditRoute,
  AdminServicesServiceIdViewRoute: AdminServicesServiceIdViewRoute,
  AdminVehiclesVehicleIdEditRoute: AdminVehiclesVehicleIdEditRoute,
  AdminVehiclesVehicleIdViewRoute: AdminVehiclesVehicleIdViewRoute,
  AdminBookingsNewIndexRoute: AdminBookingsNewIndexRoute,
  AdminClientsNewIndexRoute: AdminClientsNewIndexRoute,
  AdminReportsAuditsIndexRoute: AdminReportsAuditsIndexRoute,
  AdminServicesNewIndexRoute: AdminServicesNewIndexRoute,
  AdminVehiclesNewIndexRoute: AdminVehiclesNewIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthUnauthorizedRoute: AuthUnauthorizedRoute,
  AuthUnauthorizedModuleRoute: AuthUnauthorizedModuleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
